### ISSUE TITLE
Uncaught exception in viewPersonsWriteups

### ISSUE THREAD

**Issue by schmave** [schmave/demschooltools#46]
java.lang.NullPointerException
        at controllers.Application.viewPersonsWriteups(Application.java:632)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(Routes.scala:2136)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$15$$anonfun$apply$15.apply(Routes.scala:2136)
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
        at play.GlobalSettings$1.call(GlobalSettings.java:67)
        at controllers.Secured$AuthenticatedAction.call(Secured.java:61)
        at controllers.DumpOnError.call(DumpOnError.java:15)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:492)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
10:48:01.830 ERROR application - Error for request at /viewPersonsWriteups/6141
Headers:
  Host --> trvs.demschooltools.com|||
  Accept --> text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8|||
  Cookie --> PLAY_SESSION=1c2b4681538aff431dd297c00f9b354f6ffb617a-pa.s.id=09b2eb8a-8ba6-4117-b31d-20a36d92aacd&pa.u.exp=1442269007467&pa.p.id=google&pa.u.id=116129716600429956032&timeout=1442265913584|||
  X-Real-IP --> 98.239.240.88|||
  Connection --> close|||
  User-Agent --> Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.85 Safari/537.36|||
  Accept-Encoding --> gzip, deflate, sdch|||
  Accept-Language --> en-US,en;q=0.8|||
  X-Forwarded-For --> 98.239.240.88|||
  Upgrade-Insecure-Requests --> 1|||
Cookies:
  PLAY_SESSION --> 1c2b4681538aff431dd297c00f9b354f6ffb617a-pa.s.id=09b2eb8a-8ba6-4117-b31d-20a36d92aacd&pa.u.exp=1442269007467&pa.p.id=google&pa.u.id=116129716600429956032&timeout=1442265913584

**Comment by schmave** [comment]
Somebody just messing with URLs, found a bad ID, I think.
