### ISSUE TITLE
crash bug

### ISSUE THREAD

**Issue by schmave** [schmave/demschooltools#48]
======   1. ==
java.lang.NullPointerException
        at com.feth.play.module.pa.PlayAuthenticate.storeUser(PlayAuthenticate.java:169)
        at com.feth.play.module.pa.PlayAuthenticate.loginAndRedirect(PlayAuthenticate.java:393)
        at com.feth.play.module.pa.PlayAuthenticate.handleAuthentication(PlayAuthenticate.java:559)
        at com.feth.play.module.pa.controllers.Authenticate.authenticate(Authenticate.java:13)
        at controllers.Public.authenticate(Public.java:345)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$110$$anonfun$apply$110.apply(Routes.scala:2706)
        at router.Routes$$anonfun$routes$1$$anonfun$applyOrElse$110$$anonfun$apply$110.apply(Routes.scala:2706)
        at play.core.routing.HandlerInvokerFactory$$anon$4.resultCall(HandlerInvoker.scala:136)
        at play.core.routing.HandlerInvokerFactory$JavaActionInvokerFactory$$anon$14$$anon$3$$anon$1.invocation(HandlerInvoker.scala:127)
        at play.core.j.JavaAction$$anon$1.call(JavaAction.scala:70)
        at play.GlobalSettings$1.call(GlobalSettings.java:67)
        at controllers.DumpOnError.call(DumpOnError.java:15)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at play.core.j.JavaAction$$anonfun$7.apply(JavaAction.scala:94)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at play.core.j.HttpExecutionContext$$anon$2.run(HttpExecutionContext.scala:40)
        at play.api.libs.iteratee.Execution$trampoline$.execute(Execution.scala:70)
        at play.core.j.HttpExecutionContext.execute(HttpExecutionContext.scala:32)
        at scala.concurrent.impl.Future$.apply(Future.scala:31)
        at scala.concurrent.Future$.apply(Future.scala:492)
        at play.core.j.JavaAction.apply(JavaAction.scala:94)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4$$anonfun$apply$5.apply(Action.scala:105)
        at play.utils.Threads$.withContextClassLoader(Threads.scala:21)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:104)
        at play.api.mvc.Action$$anonfun$apply$1$$anonfun$apply$4.apply(Action.scala:103)
        at scala.Option.map(Option.scala:146)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:103)
        at play.api.mvc.Action$$anonfun$apply$1.apply(Action.scala:96)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$mapM$1.apply(Iteratee.scala:524)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMapM$1.apply(Iteratee.scala:560)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at play.api.libs.iteratee.Iteratee$$anonfun$flatMap$1$$anonfun$apply$13.apply(Iteratee.scala:536)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
        at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
14:36:52.118 ERROR application - Error for request at /authenticate/google?state=10902f98-e01c-42d1-8f32-c431e34c6db0&code=4/YmALs449L2eMDPg4AzL-3FZziXI4_xH4Dha-fiy-ICM
Headers:
  Host --> trvs.demschooltools.com|||
  Accept --> text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8|||
  Cookie --> PLAY_SESSION=e2e69c9ba62bb13401099f121b03adb064c780c2-pa.s.id=cff65f23-f312-4c5a-9fe9-3e43bba85bd9&pa.u.exp=1443209708344&pa.p.id=google&pa.u.id=116129716600429956032&timeout=1443206109716|||
  X-Real-IP --> 172.56.10.219|||
  Connection --> close|||
  User-Agent --> Mozilla/5.0 (Linux; Android 5.1.1; SM-G920T Build/LMY47X) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.94 Mobile Safari/537.36|||
  Cache-Control --> max-age=0|||
  X-Client-Data --> CKW2yQEIqbbJAQj1icoBCJaSygEIrZfKAQ==|||
  Accept-Encoding --> gzip, deflate, sdch|||
  Accept-Language --> en-US,en;q=0.8|||
  X-Forwarded-For --> 172.56.10.219|||
  X-Chrome-Connected --> id=116129716600429956032,mode=0,enable_account_consistency=true|||
  X-Chrome-UMA-Enabled --> 1|||
  Upgrade-Insecure-Requests --> 1|||
Cookies:
  PLAY_SESSION --> e2e69c9ba62bb13401099f121b03adb064c780c2-pa.s.id=cff65f23-f312-4c5a-9fe9-3e43bba85bd9&pa.u.exp=1443209708344&pa.p.id=google&pa.u.id=116129716600429956032&timeout=1443206109716

14:36:52.144 ERROR application -

**Comment by schmave** [comment]
Not in my code, not going to fix it unless it reoccurs.
